// Flat or top-marginal estimated state rates for quick estimation only.
// User can override per-source.
export const STATES: { code: string; name: string; estTopRate: number }[] = [
  { code: "NONE", name: "No state tax", estTopRate: 0 },
  { code: "AK", name: "Alaska", estTopRate: 0 },
  { code: "AL", name: "Alabama", estTopRate: 0.05 },
  { code: "AR", name: "Arkansas", estTopRate: 0.044 },
  { code: "AZ", name: "Arizona", estTopRate: 0.025 },
  { code: "CA", name: "California", estTopRate: 0.133 },
  { code: "CO", name: "Colorado", estTopRate: 0.044 },
  { code: "CT", name: "Connecticut", estTopRate: 0.0699 },
  { code: "DC", name: "District of Columbia", estTopRate: 0.1075 },
  { code: "DE", name: "Delaware", estTopRate: 0.066 },
  { code: "FL", name: "Florida", estTopRate: 0 },
  { code: "GA", name: "Georgia", estTopRate: 0.0539 },
  { code: "HI", name: "Hawaii", estTopRate: 0.11 },
  { code: "IA", name: "Iowa", estTopRate: 0.038 },
  { code: "ID", name: "Idaho", estTopRate: 0.058 },
  { code: "IL", name: "Illinois", estTopRate: 0.0495 },
  { code: "IN", name: "Indiana", estTopRate: 0.03 },
  { code: "KS", name: "Kansas", estTopRate: 0.057 },
  { code: "KY", name: "Kentucky", estTopRate: 0.04 },
  { code: "LA", name: "Louisiana", estTopRate: 0.0425 },
  { code: "MA", name: "Massachusetts", estTopRate: 0.09 },
  { code: "MD", name: "Maryland", estTopRate: 0.0575 },
  { code: "ME", name: "Maine", estTopRate: 0.0715 },
  { code: "MI", name: "Michigan", estTopRate: 0.0425 },
  { code: "MN", name: "Minnesota", estTopRate: 0.0985 },
  { code: "MO", name: "Missouri", estTopRate: 0.047 },
  { code: "MS", name: "Mississippi", estTopRate: 0.044 },
  { code: "MT", name: "Montana", estTopRate: 0.059 },
  { code: "NC", name: "North Carolina", estTopRate: 0.0425 },
  { code: "ND", name: "North Dakota", estTopRate: 0.025 },
  { code: "NE", name: "Nebraska", estTopRate: 0.052 },
  { code: "NH", name: "New Hampshire", estTopRate: 0 },
  { code: "NJ", name: "New Jersey", estTopRate: 0.1075 },
  { code: "NM", name: "New Mexico", estTopRate: 0.059 },
  { code: "NV", name: "Nevada", estTopRate: 0 },
  { code: "NY", name: "New York", estTopRate: 0.109 },
  { code: "OH", name: "Ohio", estTopRate: 0.035 },
  { code: "OK", name: "Oklahoma", estTopRate: 0.0475 },
  { code: "OR", name: "Oregon", estTopRate: 0.099 },
  { code: "PA", name: "Pennsylvania", estTopRate: 0.0307 },
  { code: "RI", name: "Rhode Island", estTopRate: 0.0599 },
  { code: "SC", name: "South Carolina", estTopRate: 0.064 },
  { code: "SD", name: "South Dakota", estTopRate: 0 },
  { code: "TN", name: "Tennessee", estTopRate: 0 },
  { code: "TX", name: "Texas", estTopRate: 0 },
  { code: "UT", name: "Utah", estTopRate: 0.0455 },
  { code: "VA", name: "Virginia", estTopRate: 0.0575 },
  { code: "VT", name: "Vermont", estTopRate: 0.0875 },
  { code: "WA", name: "Washington", estTopRate: 0 },
  { code: "WI", name: "Wisconsin", estTopRate: 0.0765 },
  { code: "WV", name: "West Virginia", estTopRate: 0.0482 },
  { code: "WY", name: "Wyoming", estTopRate: 0 },
];
